ShoppingListGraph/Models/Alert.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoppingListGraph.Models
{
    public class Alert
    {
        public const string AlertKey = "TempDataAlerts";
        public string Message { get; set; }
        public string Debug { get; set; }
    }
}

ShoppingListGraph/Models/CachedUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoppingListGraph.Models
{
    // Simple class to serialize user details
    public class CachedUser
    {
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
    }
}

ShoppingListGraph/Models/ListElement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoppingListGraph.Models
{
    public class ListElement
    {
        public string ListId { get; set; }
        public string Id { get; set; }
        public bool Completed { get; set; }
        public string Title { get; set; }
        public bool HighPriority { get; set; }
        public DateTimeOffset? CreatedDateTime { get; set; }
    }
}

ShoppingListGraph/Models/ListElementWithListId.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoppingListGraph.Models
{
    public class ListElementWithListId: ListElement
    {
        public string ListId { get; set; }
    }
}

ShoppingListGraph/Models/ListToDelete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoppingListGraph.Models
{
    public class ListToDelete
    {
        public string ListId { get; set; }
    }
}

ShoppingListGraph/Models/ThingsToBuy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShoppingListGraph.Models
{
    public class ThingsToBuy
    {
        public string Id { get; set; }
        public List<ShoppingListGraph.Models.ListElement> Elements { get; set; }

        public ThingsToBuy() {
            Elements = new List<ListElement>();
        }
    }
}

ShoppingListGraph/Controllers/AccountController.cs
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OpenIdConnect;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Claims;
using ShoppingListGraph.TokenStorage;


namespace ShoppingListGraph.Controllers
{
    public class AccountController : Controller
    {
        public void SignIn()
        {
            if (!Request.IsAuthenticated)
            {
                // Signal OWIN to send an authorization request to Azure
                Request.GetOwinContext().Authentication.Challenge(
                    new AuthenticationProperties { RedirectUri = "/" },
                    OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
        }

        public ActionResult SignOut()
        {
            if (Request.IsAuthenticated)
            {
                var tokenStore = new SessionTokenStore(null,
                    System.Web.HttpContext.Current, ClaimsPrincipal.Current);

                tokenStore.Clear();

                Request.GetOwinContext().Authentication.SignOut(
                    CookieAuthenticationDefaults.AuthenticationType);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

ShoppingListGraph/Controllers/BaseController.cs
using ShoppingListGraph.Models;
using ShoppingListGraph.TokenStorage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using Microsoft.Owin.Security.Cookies;
using System.Web.Mvc;

namespace ShoppingListGraph.Controllers
{
    public class BaseController : Controller
    {
        protected void Flash(string message, string debug = null)
        {
            var alerts = TempData.ContainsKey(Alert.AlertKey) ?
                (List<Alert>)TempData[Alert.AlertKey] :
                new List<Alert>();

            alerts.Add(new Alert
            {
                Message = message,
                Debug = debug
            });

            TempData[Alert.AlertKey] = alerts;
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (Request.IsAuthenticated)
            {
                // Get the user's token cache
                var tokenStore = new SessionTokenStore(null,
                    System.Web.HttpContext.Current, ClaimsPrincipal.Current);

                if (tokenStore.HasData())
                {
                    // Add the user to the view bag
                    ViewBag.User = tokenStore.GetUserDetails();
                }
                else
                {
                    // The session has lost data. This happens often
                    // when debugging. Log out so the user can log back in
                    Request.GetOwinContext().Authentication.SignOut(CookieAuthenticationDefaults.AuthenticationType);
                    filterContext.Result = RedirectToAction("Index", "Home");
                }
            }

            base.OnActionExecuting(filterContext);
        }
    }
}

ShoppingListGraph/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingListGraph.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Error(string message, string debug)
        {
            Flash(message, debug);
            return RedirectToAction("Index");
        }
    }
}

ShoppingListGraph/Controllers/ShoppingListController.cs
using Microsoft.Graph;
using ShoppingListGraph.Helpers;
using ShoppingListGraph.Models;
using ShoppingListGraph.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ShoppingListGraph.Controllers
{
    public class ShoppingListController : BaseController
    {
        // GET: ShoppingList
        [Authorize]
        public async Task<ActionResult> Index()
        {
            ThingsToBuyService service = new ThingsToBuyService();
            ThingsToBuy thingsToBuy = await service.GetData();
            return View(thingsToBuy);
        }

        // POST: ShoppingList
        [Authorize, HttpPost]
        public async Task<ActionResult> Index(ThingsToBuy edit)
        {
            ThingsToBuyService service = new ThingsToBuyService();
            //Save changes
            ThingsToBuy thingsToBuy = await service.SaveChanges(edit);
            return View(thingsToBuy);
        }

        //GET: Create ListElement
        [Authorize]
        public ActionResult Create(string id)
        {
            return View(new ListElementWithListId() { Id = null, ListId = id });
        }

        [Authorize, HttpPost]
        public async Task<ActionResult> Create(ListElementWithListId listElement)
        {
            ThingsToBuyService service = new ThingsToBuyService();
            await service.CreateListElement(listElement);
            return RedirectToAction("Index");
        }

        //Empty list

        [Authorize]
        public ActionResult Delete(string id)
        {
            return View(new ListToDelete() { ListId = id });

        }

        [Authorize, HttpPost]
        public async Task<ActionResult> Delete(ListToDelete list)
        {
            ThingsToBuyService service = new ThingsToBuyService();
            await service.ResetList(list.ListId);
            return RedirectToAction("Index");
        }
    }
}

ShoppingListGraph/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

ShoppingListGraph/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

ShoppingListGraph/Views/Home/Index.cshtml
@{
    ViewBag.Current = "Home";
}

<div>
    <div class="jumbotron">
        <h1>Shopping List Graph</h1>

        <p class="lead">Maintain your shopping list using the Microsoft Graph API</p>
    </div>
    @if (Request.IsAuthenticated)
    {
        <h4>Welcome @ViewBag.User.DisplayName!</h4>
        <p>Use the navigation bar at the top of the page to get started.</p>
    }
    else
    {
        @Html.ActionLink("Click here to sign in", "SignIn", "Account", new { area = "" }, new { @class = "btn btn-primary btn-large" })
    }
</div>

ShoppingListGraph/Views/Shared/_Layout.cshtml
@{
    var alerts = TempData.ContainsKey(ShoppingListGraph.Models.Alert.AlertKey)
        ? (List<ShoppingListGraph.Models.Alert>)TempData[ShoppingListGraph.Models.Alert.AlertKey]
        : new List<ShoppingListGraph.Models.Alert>();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shopping List Graph</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
          integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
          crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://cdn-icons-png.flaticon.com/512/1238/1238942.png" sizes="32x32">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container">
            @Html.ActionLink("Shopping List Graph", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", new { area = "" },
                            new { @class = ViewBag.Current == "Home" ? "nav-link active" : "nav-link" })
                    </li>
                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item" data-turbolinks="false">
                            @Html.ActionLink("Shopping list", "Index", "ShoppingList", new { area = "" },
                                new { @class = ViewBag.Current == "ShoppingList" ? "nav-link active shoppinglistbtn" : "nav-link shoppinglistbtn" })
                        </li>
                    }
                </ul>
                <ul class="navbar-nav justify-content-end" style="align-items:center;width: 100%;">
                    @if (Request.IsAuthenticated)
                    {
                        @*<li>
                <div style="color:white">Connected as
                    <h5 class="dropdown-item-text mb-0">@ViewBag.User.DisplayName</h5>
                    <p class="dropdown-item-text text-muted mb-0">@ViewBag.User.Email</p>
                    <div class="dropdown-divider"></div>
                    @Html.ActionLink("Sign Out", "SignOut", "Account", new { area = "" }, new { @class = "dropdown-item" })
                </div>
            </li>*@
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                @if (!string.IsNullOrEmpty(ViewBag.User.Avatar))
                                {
                                    <img src="@ViewBag.User.Avatar" class="rounded-circle align-self-center mr-2" style="width: 32px;">
                                }
                                else
                                {
                                    <i class="far fa-user-circle fa-lg rounded-circle align-self-center mr-2" style="width: 32px;"></i>
                                }
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <h5 class="dropdown-item-text mb-0">@ViewBag.User.DisplayName</h5>
                                <p class="dropdown-item-text text-muted mb-0">@ViewBag.User.Email</p>
                                <div class="dropdown-divider"></div>
                                @Html.ActionLink("Sign Out", "SignOut", "Account", new { area = "" }, new { @class = "dropdown-item" })
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Sign In", "SignIn", "Account", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <main role="main" class="container">
        @foreach (var alert in alerts)
        {
            <div class="alert alert-danger" role="alert">
                <p class="mb-3">@alert.Message</p>
                @if (!string.IsNullOrEmpty(alert.Debug))
                {
                    <pre class="alert-pre border bg-light p-2"><code>@alert.Debug</code></pre>
                }
            </div>
        }

        @RenderBody()
    </main>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShoppingListGraph/Views/ShoppingList/Create.cshtml
@model ShoppingListGraph.Models.ListElementWithListId

@{
    ViewBag.Title = "Add item";
}

<h2>Add item</h2>

@using (Html.BeginForm()) 
{
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ListId)
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HighPriority, labelText:"High priority", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    
                    @Html.EditorFor(model => model.HighPriority, new { htmlAttributes = new { @class = "chkHighPriorityCreate" } })
                    @Html.ValidationMessageFor(model => model.HighPriority, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary btn-large" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShoppingListGraph/Views/ShoppingList/Delete.cshtml
@model ShoppingListGraph.Models.ListToDelete

@{
    ViewBag.Title = "Clear list";
}

<h2>Clear list</h2>

@using (Html.BeginForm()) 
{
    
    <div class="form-horizontal">
        <h5>List will be clear. Are you sure?</h5>
        <hr />

        @Html.HiddenFor(model => model.ListId)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Delete" class="btn btn-primary btn-large" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShoppingListGraph/Views/ShoppingList/Index.cshtml
@model ShoppingListGraph.Models.ThingsToBuy


@{
    ViewBag.Current = "ShoppingList";
}

<h1>Shopping list</h1>
@Html.ActionLink("Add item", "Create", "ShoppingList", new { id = Model.Id}, new { @class = "btnCreateItem" })
@Html.ActionLink("Clear list", "Delete", "ShoppingList", new { id = Model.Id }, null)
@using (Html.BeginForm("Index", "ShoppingList", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Status</th>
                <th scope="col">Item</th>
                <th scope="col">High priority</th>
                @*<th scope="col">Created</th>*@
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Elements.Count; i++)
            {
                <tr>

                    <td>
                        @Html.HiddenFor(m => m.Elements[i].Id)
                        @Html.CheckBoxFor(m => m.Elements[i].Completed,
                                new
                                     {
                                         @class = "chkCompleted",
                                    onclick = "this.form.submit();"
                                })
                    </td>
                    <td class=@String.Format("{0}", Model.Elements[i].Completed ? "titleCompleted" : string.Empty)>
                        @Html.DisplayFor(m => m.Elements[i].Title)
                    </td>
                    <td>
                        @Html.CheckBoxFor(m => m.Elements[i].HighPriority,
                                new
                                     {
                                         @class = "chkHighPriority",
                                    onclick = "this.form.submit();"
                                })
                    </td>
                    @*<td>@Convert.ToDateTime(item.CreatedDateTime).ToString("M/d/yy h:mm tt")</td>*@
                </tr>
            }
        </tbody>
    </table>
}